server:
  port: 8888

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/smbms?serverTimeZone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html
    mode: HTML5
    encoding: UTF-8


